stages:
  - deploy

deploy:
  stage: deploy
  image: maven:3.6-jdk-11
  script:
    - echo "$MAVEN_SETTINGS" > ~/.m2/settings.xml
    - mvn clean deploy -P traineeshipTemplateDeploy, traineeshipPomTemplate
